### ISSUE TITLE
Remove or implement unused parameters in ocf_datapipes/config/model.py

### ISSUE THREAD

**Issue by AUdaltsova** [openclimatefix/ocf_datapipes#324]
Two arguments are never used:
- `get_center`: available in source models for PV, Wind, Sensor
- `data_source_which_defines_geospatial_locations`: in InputData

Both seem to define which source is used for location, which is currently implemented through an ordered list of keys (see: `ocf_datapipes.training.common.construct_loctime_pipelines`). They found their way into some data config files, so should we implement/remove them to avoid confusion?

As far as I can see, they both serve the same function and it would probably be easier and/or better for cohesion to implement  `data_source_which_defines_geospatial_locations` as an optional source of location key. Will require adjustment though, since using different sources for time and location is (I think) not possible as of now.

Thoughts?

_______________

Edit:
Should be removed as not used anywhere

**Comment by dfulu** [comment]
If they are not being used I'm in favour of stripping them out. I think there are still chunks of `ocf_datapipes` which were copied over from `nowcasting_dataloader` and other places which were never used. Good spot

**Comment by peterdudfield** [comment]
yea, if they arent being used, I would strip them out

**Comment by Sukh-P** [comment]
Just an FYI I have removed these unused parameters from some data configs we had on HF [here](https://huggingface.co/openclimatefix/windnet_india/commit/ae07c15de064e1d03cf4bc02618b65c6d5b17e8e) and [here](https://huggingface.co/openclimatefix/pvnet_india/commit/d71104620f0b0bdd3eeb63cafecd2a49032ae0f7) since they were causing issues with pydantic validation now that they have been removed
