### ISSUE TITLE
issue in openclimatefix/ocf_datapipes 

### ISSUE THREAD

**Issue by SophiaLi20** [openclimatefix/ocf_datapipes#368]
in the readme section where the usage is described and for their usage the link provided can't be opened as it has been displaying the page not found error [https://pytorch.org/data/main/examples.html](https://pytorch.org/data/main/examples.html) .
![Screenshot (70)](https://github.com/user-attachments/assets/d6256721-893f-4a38-8e25-b7b470b37b65)

If not needed we can remove this link also as it only describes the usage of docs.

**Comment by Sukh-P** [comment]
Hi @SophiaLi20,

Thanks for raising this, I have now raised a PR to update this link, it is worth noting that I am also updating the note in the README to a warning that this repo is not going to be supported in the near future and we are moving towards the [ocf-data-sampler](https://github.com/openclimatefix/ocf-data-sampler) library for our data processing pipeline.

 If you want more detail for torch datapipes specifically, you can look at the [source code](https://github.com/pytorch/pytorch/blob/main/torch/utils/data/datapipes/datapipe.py) also you can see the issue where we discussed moving away from datapipes in TorchData specifically since that is no longer supported here https://github.com/openclimatefix/ocf_datapipes/issues/307, thanks

**Comment by SophiaLi20** [comment]
You're welcome! Please feel free to reach out if there's anything else I can help with.

**Comment by SophiaLi20** [comment]
You are welcome @Sukh-P ! Please feel free to reach out if there's anything else i can help with
